### ISSUE TITLE
Evaluate code gen to build pydantic models from JSON schema

### ISSUE THREAD

**Issue by geospatial-jeff** [stac-utils/stac-pydantic#84]
@kylebarron mentioned this project is becoming more mature, might be worth looking into how useful it is here. 
 Would be really nice to programmatically generate pydantic models from the JSON schema fragments provided by the spec. 

 https://github.com/koxudaxi/datamodel-code-generator

**Comment by kylebarron** [comment]
Some notes copied from slack. From inside `item-spec/json-schema` try:

```
datamodel-codegen \
  --input item.json \
  --input-file-type jsonschema --class-name Item \
  --output item \
  `# Alias camelcase fields to snake case for Python` \
  --snake-case-field \
  `# Set top-level "description" field as Python class docstring` \
  --use-schema-description \
  `# Allow creating the Pydantic model using both the alias and the field name` \
  --allow-population-by-field-name
```

And the output pydantic models will be in the `item` folder (with an `__init__.py` so you can just do `import item`.

It’s not perfect still... for example the `datetime` field is created as a `str` type instead of a `datetime` type:
```py
    datetime: Optional[Optional[str]] = Field(
        None,
        description='The searchable date/time of the assets, in UTC (Formatted in RFC 3339) ',
        title='Date and Time',
    )
```

This is because the [source JSON Schema](https://github.com/radiantearth/stac-spec/blob/789e90fba4c7119bc925d26f75f47bacf44c91e6/item-spec/json-schema/datetime.json#L19-L23) has `format: date-time` but also has `"type": ["string", "null"],`. Adding `null` into the allowed types trips up the generator. Compare that to the [other fields in the spec](https://github.com/radiantearth/stac-spec/blob/789e90fba4c7119bc925d26f75f47bacf44c91e6/item-spec/json-schema/datetime.json#L26-L51) that are declared as only `type: string`, which are accurately set as `datetime`:

```py
    start_datetime: Optional[datetime] = Field(
        None,
        description='The searchable start date/time of the assets, in UTC (Formatted in RFC 3339) ',
        title='Start Date and Time',
    )
    end_datetime: Optional[datetime] = Field(
        None,
        description='The searchable end date/time of the assets, in UTC (Formatted in RFC 3339) ',
        title='End Date and Time',
    )
    created: Optional[datetime] = Field(None, title='Creation Time')
    updated: Optional[datetime] = Field(None, title='Last Update Time')
```

**Comment by kylebarron** [comment]
One thing that might be difficult with Pydantic is its support for model unions in relation to extensions. In a language like typescript, you could do `Item & EOExtension` to declare the type of an item that also matches the EO extension spec. I'm not sure how easy that would be in Pydantic. Though I also don't know exactly how extensions are currently handled.

**Comment by vincentsarago** [comment]
duplicated of https://github.com/stac-utils/stac-pydantic/issues/50
